// ============================================================
// SKILL TREE DATA - 8 DOMAINS
// Each domain: { id, name, color, skills[] }
// Each skill: { id, name, tier, prereqs[], crossDomain[] }
// crossDomain: [{ target: "domain.skillId", label: "description" }]
// ============================================================

export const DOMAINS = [
  {
    id: "math",
    name: "Mathematics",
    color: "#3B82F6",
    colorDark: "#1E40AF",
    icon: "∑",
    skills: [
      // TIER 1
      { id: "counting", name: "Counting", tier: 1, prereqs: [], crossDomain: [{ target: "lang.basic_vocab", label: "Number words" }] },
      { id: "number_recognition", name: "Number Recognition", tier: 1, prereqs: ["counting"], crossDomain: [{ target: "lang.letter_recognition", label: "Symbol recognition" }] },
      { id: "basic_addition", name: "Basic Addition", tier: 1, prereqs: ["counting", "number_recognition"], crossDomain: [{ target: "lang.basic_vocab", label: "Math vocabulary" }] },
      { id: "basic_subtraction", name: "Basic Subtraction", tier: 1, prereqs: ["counting", "number_recognition", "basic_addition"], crossDomain: [] },
      // TIER 2
      { id: "place_value", name: "Place Value", tier: 2, prereqs: ["counting", "number_recognition", "basic_addition"], crossDomain: [] },
      { id: "multiplication", name: "Multiplication", tier: 2, prereqs: ["basic_addition", "place_value"], crossDomain: [] },
      { id: "division", name: "Division", tier: 2, prereqs: ["multiplication", "basic_subtraction"], crossDomain: [{ target: "lang.reading_comp", label: "Word problems" }] },
      { id: "fractions", name: "Fractions", tier: 2, prereqs: ["division", "place_value", "multiplication"], crossDomain: [] },
      { id: "decimals", name: "Decimals", tier: 2, prereqs: ["fractions", "place_value"], crossDomain: [] },
      { id: "measurement", name: "Measurement", tier: 2, prereqs: ["basic_addition", "basic_subtraction", "decimals"], crossDomain: [{ target: "fitness.endurance", label: "Timing/distance" }] },
      { id: "time_math", name: "Time", tier: 2, prereqs: ["basic_addition", "basic_subtraction", "place_value"], crossDomain: [{ target: "life.telling_time", label: "Clock reading" }] },
      { id: "money_math", name: "Money", tier: 2, prereqs: ["counting", "decimals", "basic_addition"], crossDomain: [{ target: "life.money_counting", label: "Currency" }] },
      // TIER 3
      { id: "ratios", name: "Ratios", tier: 3, prereqs: ["fractions", "division", "multiplication"], crossDomain: [{ target: "life.budgeting", label: "Proportional spending" }] },
      { id: "proportions", name: "Proportions", tier: 3, prereqs: ["ratios"], crossDomain: [{ target: "creative.color_theory", label: "Color mixing ratios" }] },
      { id: "percentages", name: "Percentages", tier: 3, prereqs: ["ratios", "decimals"], crossDomain: [{ target: "life.budgeting", label: "Interest/discounts" }, { target: "social.econ_basics", label: "Economic data" }] },
      { id: "order_of_ops", name: "Order of Operations", tier: 3, prereqs: ["multiplication", "division", "basic_addition", "basic_subtraction"], crossDomain: [] },
      { id: "integers", name: "Integers", tier: 3, prereqs: ["basic_subtraction", "number_recognition"], crossDomain: [] },
      { id: "coordinate_plane", name: "Coordinate Plane", tier: 3, prereqs: ["integers", "number_recognition"], crossDomain: [{ target: "social.map_globe", label: "Lat/Long" }, { target: "tech.spreadsheets", label: "Charting data" }] },
      { id: "basic_geometry", name: "Basic Geometry", tier: 3, prereqs: ["measurement", "multiplication"], crossDomain: [{ target: "creative.design_principles", label: "Composition" }] },
      // TIER 4
      { id: "variables_expr", name: "Variables & Expressions", tier: 4, prereqs: ["order_of_ops", "integers"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Variables in code" }] },
      { id: "linear_equations", name: "Linear Equations", tier: 4, prereqs: ["variables_expr"], crossDomain: [{ target: "social.microeconomics", label: "Supply/demand curves" }] },
      { id: "inequalities", name: "Inequalities", tier: 4, prereqs: ["linear_equations"], crossDomain: [] },
      { id: "functions", name: "Functions", tier: 4, prereqs: ["linear_equations", "coordinate_plane"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Functions in code" }] },
      { id: "graphing", name: "Graphing", tier: 4, prereqs: ["coordinate_plane", "functions"], crossDomain: [{ target: "tech.spreadsheets", label: "Data visualization" }] },
      { id: "systems_of_eq", name: "Systems of Equations", tier: 4, prereqs: ["linear_equations"], crossDomain: [] },
      { id: "polynomials", name: "Polynomials", tier: 4, prereqs: ["variables_expr", "multiplication"], crossDomain: [] },
      { id: "factoring", name: "Factoring", tier: 4, prereqs: ["polynomials"], crossDomain: [] },
      // TIER 5
      { id: "euclidean_geo", name: "Euclidean Geometry", tier: 5, prereqs: ["basic_geometry", "linear_equations"], crossDomain: [{ target: "creative.design_principles", label: "Golden ratio" }] },
      { id: "proofs", name: "Proofs & Logic", tier: 5, prereqs: ["euclidean_geo"], crossDomain: [{ target: "lang.essay_writing", label: "Logical argument" }, { target: "religion.apologetics", label: "Logical reasoning" }] },
      { id: "triangles_cong", name: "Triangles & Congruence", tier: 5, prereqs: ["euclidean_geo"], crossDomain: [] },
      { id: "circles_geo", name: "Circles", tier: 5, prereqs: ["euclidean_geo"], crossDomain: [] },
      { id: "transformations", name: "Transformations", tier: 5, prereqs: ["coordinate_plane", "euclidean_geo"], crossDomain: [{ target: "tech.computer_graphics", label: "Transform matrices" }] },
      { id: "trig_ratios", name: "Trigonometric Ratios", tier: 5, prereqs: ["triangles_cong", "ratios"], crossDomain: [{ target: "fitness.biomechanics", label: "Angle analysis" }] },
      { id: "solid_geometry", name: "Solid Geometry", tier: 5, prereqs: ["euclidean_geo", "basic_geometry"], crossDomain: [] },
      // TIER 6
      { id: "quadratics", name: "Quadratic Functions", tier: 6, prereqs: ["factoring", "functions", "graphing"], crossDomain: [{ target: "fitness.biomechanics", label: "Projectile motion" }] },
      { id: "exponential_log", name: "Exponential & Log Functions", tier: 6, prereqs: ["functions"], crossDomain: [{ target: "life.investing", label: "Compound interest" }] },
      { id: "sequences_series", name: "Sequences & Series", tier: 6, prereqs: ["functions", "variables_expr"], crossDomain: [{ target: "creative.music_composition", label: "Patterns" }] },
      { id: "matrices", name: "Matrices", tier: 6, prereqs: ["systems_of_eq", "variables_expr"], crossDomain: [{ target: "tech.computer_graphics", label: "3D transforms" }] },
      { id: "complex_numbers", name: "Complex Numbers", tier: 6, prereqs: ["quadratics"], crossDomain: [] },
      { id: "conic_sections", name: "Conic Sections", tier: 6, prereqs: ["quadratics", "circles_geo"], crossDomain: [] },
      // TIER 7
      { id: "limits", name: "Limits", tier: 7, prereqs: ["functions", "graphing"], crossDomain: [] },
      { id: "derivatives", name: "Derivatives", tier: 7, prereqs: ["limits", "polynomials"], crossDomain: [{ target: "fitness.exercise_physiology", label: "Rate of change" }] },
      { id: "integrals", name: "Integrals", tier: 7, prereqs: ["derivatives"], crossDomain: [] },
      { id: "trig_functions", name: "Trigonometric Functions", tier: 7, prereqs: ["trig_ratios", "functions"], crossDomain: [] },
      { id: "polar_coords", name: "Polar Coordinates", tier: 7, prereqs: ["trig_functions", "coordinate_plane"], crossDomain: [] },
      { id: "vectors_math", name: "Vectors", tier: 7, prereqs: ["trig_ratios", "matrices"], crossDomain: [{ target: "tech.computer_graphics", label: "3D graphics" }] },
      // TIER 8
      { id: "multivariable_calc", name: "Multivariable Calculus", tier: 8, prereqs: ["integrals", "vectors_math"], crossDomain: [{ target: "tech.advanced_ml", label: "Gradient descent" }] },
      { id: "diff_equations", name: "Differential Equations", tier: 8, prereqs: ["integrals"], crossDomain: [{ target: "fitness.sports_science", label: "Growth models" }] },
      { id: "linear_algebra", name: "Linear Algebra", tier: 8, prereqs: ["matrices", "vectors_math"], crossDomain: [{ target: "tech.advanced_ml", label: "Neural networks" }] },
      { id: "discrete_math", name: "Discrete Math", tier: 8, prereqs: ["proofs", "functions"], crossDomain: [{ target: "tech.data_structures", label: "Graph theory" }] },
      { id: "probability_theory", name: "Probability Theory", tier: 8, prereqs: ["integrals", "sequences_series"], crossDomain: [{ target: "social.game_theory", label: "Expected value" }, { target: "tech.advanced_ml", label: "Bayesian methods" }] },
      { id: "number_theory", name: "Number Theory", tier: 8, prereqs: ["proofs", "integers"], crossDomain: [{ target: "tech.cryptography", label: "RSA/primes" }] },
      { id: "real_analysis", name: "Real Analysis", tier: 8, prereqs: ["limits", "proofs", "sequences_series"], crossDomain: [] },
      { id: "abstract_algebra", name: "Abstract Algebra", tier: 8, prereqs: ["proofs", "matrices"], crossDomain: [{ target: "tech.cryptography", label: "Group theory" }] },
    ]
  },
  {
    id: "lang",
    name: "Language",
    color: "#F59E0B",
    colorDark: "#B45309",
    icon: "A",
    skills: [
      // TIER 1
      { id: "phonemic_awareness", name: "Phonemic Awareness", tier: 1, prereqs: [], crossDomain: [] },
      { id: "letter_recognition", name: "Letter Recognition", tier: 1, prereqs: [], crossDomain: [{ target: "math.number_recognition", label: "Symbol decoding" }] },
      { id: "basic_vocab", name: "Basic Vocabulary", tier: 1, prereqs: [], crossDomain: [{ target: "religion.bible_stories", label: "Story vocabulary" }] },
      { id: "listening_comp", name: "Listening Comprehension", tier: 1, prereqs: [], crossDomain: [{ target: "social.community_awareness", label: "Social listening" }] },
      // TIER 2
      { id: "phonics", name: "Phonics & Decoding", tier: 2, prereqs: ["phonemic_awareness", "letter_recognition"], crossDomain: [] },
      { id: "sight_words", name: "Sight Words", tier: 2, prereqs: ["letter_recognition"], crossDomain: [] },
      { id: "reading_fluency", name: "Basic Reading Fluency", tier: 2, prereqs: ["phonics", "sight_words"], crossDomain: [{ target: "religion.ot_survey", label: "Bible reading" }] },
      { id: "handwriting", name: "Handwriting", tier: 2, prereqs: ["letter_recognition"], crossDomain: [{ target: "creative.basic_drawing", label: "Fine motor" }] },
      { id: "spelling", name: "Spelling", tier: 2, prereqs: ["phonics", "letter_recognition"], crossDomain: [] },
      { id: "sentence_structure", name: "Basic Sentence Structure", tier: 2, prereqs: ["basic_vocab", "spelling"], crossDomain: [] },
      // TIER 3
      { id: "reading_comp", name: "Reading Comprehension", tier: 3, prereqs: ["reading_fluency", "basic_vocab"], crossDomain: [{ target: "math.ratios", label: "Word problems" }, { target: "social.ancient_civs", label: "Historical texts" }, { target: "religion.life_of_christ", label: "Scripture study" }] },
      { id: "grammar", name: "Grammar", tier: 3, prereqs: ["sentence_structure", "spelling"], crossDomain: [] },
      { id: "paragraph_writing", name: "Paragraph Writing", tier: 3, prereqs: ["sentence_structure", "grammar"], crossDomain: [] },
      { id: "expanded_vocab", name: "Expanded Vocabulary", tier: 3, prereqs: ["reading_comp", "basic_vocab"], crossDomain: [] },
      { id: "dictionary_skills", name: "Dictionary Skills", tier: 3, prereqs: ["reading_fluency", "spelling"], crossDomain: [] },
      // TIER 4
      { id: "essay_writing", name: "Essay Writing", tier: 4, prereqs: ["paragraph_writing", "grammar"], crossDomain: [{ target: "social.critical_analysis", label: "Source-based essays" }, { target: "religion.hermeneutics", label: "Exegetical papers" }] },
      { id: "literary_analysis", name: "Literary Analysis", tier: 4, prereqs: ["reading_comp", "expanded_vocab"], crossDomain: [{ target: "social.us_hist_rev", label: "Period literature" }] },
      { id: "figurative_lang", name: "Figurative Language", tier: 4, prereqs: ["reading_comp", "expanded_vocab"], crossDomain: [{ target: "religion.parables", label: "Parable interpretation" }, { target: "creative.poetry", label: "Poetic devices" }] },
      { id: "research_skills", name: "Research Skills", tier: 4, prereqs: ["reading_comp", "dictionary_skills"], crossDomain: [{ target: "tech.internet_search", label: "Digital research" }, { target: "social.critical_analysis", label: "Source evaluation" }] },
      { id: "note_taking", name: "Note-Taking", tier: 4, prereqs: ["reading_comp", "handwriting"], crossDomain: [{ target: "life.study_skills", label: "Study methods" }] },
      { id: "public_speaking_basic", name: "Public Speaking Basics", tier: 4, prereqs: ["paragraph_writing", "expanded_vocab"], crossDomain: [{ target: "religion.homiletics", label: "Preaching skills" }, { target: "life.job_interview", label: "Interview presence" }] },
      // TIER 5
      { id: "persuasive_writing", name: "Persuasive Writing", tier: 5, prereqs: ["essay_writing", "literary_analysis"], crossDomain: [{ target: "social.media_literacy", label: "Propaganda analysis" }] },
      { id: "comparative_analysis", name: "Comparative Analysis", tier: 5, prereqs: ["literary_analysis", "essay_writing"], crossDomain: [{ target: "social.comparative_gov", label: "Comparing systems" }] },
      { id: "rhetoric", name: "Rhetoric", tier: 5, prereqs: ["persuasive_writing", "figurative_lang"], crossDomain: [{ target: "social.political_sci", label: "Political rhetoric" }, { target: "religion.apologetics", label: "Persuasive defense" }] },
      { id: "adv_grammar", name: "Advanced Grammar", tier: 5, prereqs: ["grammar", "essay_writing"], crossDomain: [] },
      { id: "creative_writing", name: "Creative Writing", tier: 5, prereqs: ["figurative_lang", "paragraph_writing"], crossDomain: [{ target: "creative.screenwriting", label: "Narrative craft" }] },
      { id: "debate", name: "Debate", tier: 5, prereqs: ["rhetoric", "public_speaking_basic", "research_skills"], crossDomain: [{ target: "social.political_sci", label: "Policy debate" }, { target: "religion.apologetics", label: "Defense of faith" }] },
      // TIER 6
      { id: "academic_writing", name: "Academic Writing", tier: 6, prereqs: ["persuasive_writing", "adv_grammar", "research_skills"], crossDomain: [{ target: "social.ap_history", label: "DBQ essays" }] },
      { id: "literary_criticism", name: "Literary Criticism", tier: 6, prereqs: ["comparative_analysis", "literary_analysis"], crossDomain: [] },
      { id: "linguistics_basics", name: "Linguistics Basics", tier: 6, prereqs: ["adv_grammar", "phonemic_awareness"], crossDomain: [{ target: "social.anthropology", label: "Linguistic anthropology" }] },
      { id: "adv_rhetoric", name: "Advanced Rhetoric", tier: 6, prereqs: ["rhetoric", "academic_writing"], crossDomain: [] },
      { id: "technical_writing", name: "Technical Writing", tier: 6, prereqs: ["academic_writing"], crossDomain: [{ target: "tech.software_eng", label: "Documentation" }] },
      { id: "journalism", name: "Journalism", tier: 6, prereqs: ["research_skills", "persuasive_writing"], crossDomain: [{ target: "social.media_literacy", label: "News production" }] },
      // TIER 7
      { id: "research_papers", name: "Research Papers", tier: 7, prereqs: ["academic_writing", "research_skills"], crossDomain: [{ target: "social.research_methodology", label: "Methods" }] },
      { id: "thesis_development", name: "Thesis Development", tier: 7, prereqs: ["research_papers"], crossDomain: [] },
      { id: "semiotics", name: "Semiotics", tier: 7, prereqs: ["linguistics_basics", "literary_criticism"], crossDomain: [{ target: "creative.art_criticism", label: "Visual semiotics" }] },
      { id: "discourse_analysis", name: "Discourse Analysis", tier: 7, prereqs: ["linguistics_basics", "adv_rhetoric"], crossDomain: [{ target: "social.historiography", label: "Text analysis" }] },
      { id: "prof_communication", name: "Professional Communication", tier: 7, prereqs: ["technical_writing", "adv_rhetoric"], crossDomain: [{ target: "life.career_planning", label: "Workplace writing" }] },
      { id: "editing_revision", name: "Editing & Revision", tier: 7, prereqs: ["academic_writing", "adv_grammar"], crossDomain: [] },
      // TIER 8
      { id: "academic_publishing", name: "Academic Publishing", tier: 8, prereqs: ["thesis_development", "editing_revision"], crossDomain: [{ target: "religion.theological_research", label: "Theological journals" }] },
      { id: "translation_theory", name: "Translation Theory", tier: 8, prereqs: ["linguistics_basics", "semiotics"], crossDomain: [{ target: "religion.biblical_languages_adv", label: "Bible translation" }] },
      { id: "comp_linguistics", name: "Computational Linguistics", tier: 8, prereqs: ["linguistics_basics", "discourse_analysis"], crossDomain: [{ target: "tech.advanced_ml", label: "NLP" }, { target: "math.linear_algebra", label: "Vector spaces" }] },
      { id: "literary_theory", name: "Literary Theory", tier: 8, prereqs: ["literary_criticism", "semiotics"], crossDomain: [] },
      { id: "screenwriting_lang", name: "Screenwriting", tier: 8, prereqs: ["creative_writing", "literary_criticism"], crossDomain: [{ target: "creative.film_production", label: "Film scripts" }] },
      { id: "grant_writing", name: "Grant Writing", tier: 8, prereqs: ["academic_writing", "research_papers"], crossDomain: [{ target: "life.entrepreneurship", label: "Funding proposals" }] },
    ]
  },
  {
    id: "social",
    name: "Social Studies",
    color: "#10B981",
    colorDark: "#047857",
    icon: "🌍",
    skills: [
      // TIER 1
      { id: "community_awareness", name: "Community Awareness", tier: 1, prereqs: [], crossDomain: [{ target: "religion.church_community", label: "Church as community" }, { target: "life.basic_manners", label: "Social norms" }] },
      { id: "family_structures", name: "Family Structures", tier: 1, prereqs: ["community_awareness"], crossDomain: [{ target: "religion.gods_love", label: "God's family" }] },
      { id: "basic_maps", name: "Basic Maps", tier: 1, prereqs: [], crossDomain: [{ target: "math.coordinate_plane", label: "Grid systems" }] },
      { id: "rules_laws", name: "Rules & Laws", tier: 1, prereqs: ["community_awareness"], crossDomain: [{ target: "religion.ten_commandments", label: "Moral law" }] },
      { id: "sharing_coop", name: "Sharing & Cooperation", tier: 1, prereqs: [], crossDomain: [{ target: "life.sharing_turns", label: "Turn-taking" }, { target: "fitness.team_sports_intro", label: "Teamwork" }] },
      // TIER 2
      { id: "us_geography", name: "US Geography", tier: 2, prereqs: ["basic_maps"], crossDomain: [] },
      { id: "world_geography", name: "World Geography", tier: 2, prereqs: ["basic_maps", "us_geography"], crossDomain: [{ target: "religion.biblical_geography", label: "Holy Land" }] },
      { id: "timeline_chrono", name: "Timeline & Chronology", tier: 2, prereqs: ["community_awareness"], crossDomain: [{ target: "math.number_recognition", label: "Number lines" }] },
      { id: "cultural_awareness", name: "Cultural Awareness", tier: 2, prereqs: ["family_structures"], crossDomain: [{ target: "religion.denominational", label: "Christian diversity" }, { target: "creative.dance_basics", label: "Cultural dance" }] },
      { id: "citizenship_basics", name: "Citizenship Basics", tier: 2, prereqs: ["rules_laws"], crossDomain: [{ target: "life.basic_manners", label: "Civic behavior" }] },
      { id: "historical_figures", name: "Historical Figures", tier: 2, prereqs: ["timeline_chrono", "community_awareness"], crossDomain: [{ target: "lang.reading_fluency", label: "Biographies" }] },
      // TIER 3
      { id: "ancient_civs", name: "Ancient Civilizations", tier: 3, prereqs: ["timeline_chrono", "world_geography"], crossDomain: [{ target: "religion.ot_survey", label: "Ancient Israel" }] },
      { id: "world_religions_overview", name: "World Religions Overview", tier: 3, prereqs: ["cultural_awareness", "ancient_civs"], crossDomain: [{ target: "religion.denominational", label: "Christianity in context" }] },
      { id: "us_hist_colonial", name: "US History: Colonial", tier: 3, prereqs: ["historical_figures", "us_geography"], crossDomain: [{ target: "religion.church_hist_basics", label: "Colonial religion" }] },
      { id: "gov_structure", name: "Government Structure", tier: 3, prereqs: ["citizenship_basics", "rules_laws"], crossDomain: [] },
      { id: "econ_basics", name: "Economics Basics", tier: 3, prereqs: ["community_awareness"], crossDomain: [{ target: "math.graphing", label: "Supply/demand curves" }, { target: "life.budgeting", label: "Personal economics" }] },
      { id: "map_globe", name: "Map & Globe Skills", tier: 3, prereqs: ["us_geography", "world_geography"], crossDomain: [{ target: "math.coordinate_plane", label: "Coordinates" }] },
      // TIER 4
      { id: "us_hist_rev", name: "US History: Revolution–Civil War", tier: 4, prereqs: ["us_hist_colonial", "gov_structure"], crossDomain: [{ target: "lang.essay_writing", label: "Primary sources" }] },
      { id: "world_hist_medieval", name: "World History: Medieval–Renaissance", tier: 4, prereqs: ["ancient_civs", "world_religions_overview"], crossDomain: [{ target: "religion.church_hist_reformation", label: "Reformation" }, { target: "creative.art_history", label: "Renaissance art" }] },
      { id: "civics_gov", name: "Civics & Government", tier: 4, prereqs: ["gov_structure", "us_hist_rev"], crossDomain: [{ target: "religion.christian_ethics", label: "Moral governance" }] },
      { id: "microeconomics", name: "Microeconomics", tier: 4, prereqs: ["econ_basics"], crossDomain: [{ target: "math.linear_equations", label: "Economic models" }] },
      { id: "sociology_basics", name: "Sociology Basics", tier: 4, prereqs: ["cultural_awareness", "ancient_civs"], crossDomain: [{ target: "religion.ecclesiology", label: "Church sociology" }] },
      { id: "critical_analysis", name: "Critical Analysis of Sources", tier: 4, prereqs: ["historical_figures", "timeline_chrono"], crossDomain: [{ target: "lang.research_skills", label: "Source evaluation" }, { target: "tech.internet_search", label: "Digital sources" }] },
      // TIER 5
      { id: "us_hist_modern", name: "US History: Modern", tier: 5, prereqs: ["us_hist_rev"], crossDomain: [] },
      { id: "world_hist_modern", name: "World History: Modern", tier: 5, prereqs: ["world_hist_medieval"], crossDomain: [] },
      { id: "macroeconomics", name: "Macroeconomics", tier: 5, prereqs: ["microeconomics"], crossDomain: [{ target: "math.functions", label: "Economic functions" }, { target: "life.financial_planning", label: "Personal finance context" }] },
      { id: "political_sci", name: "Political Science", tier: 5, prereqs: ["civics_gov", "sociology_basics"], crossDomain: [{ target: "religion.public_theology", label: "Faith & politics" }] },
      { id: "anthropology", name: "Anthropology", tier: 5, prereqs: ["sociology_basics", "ancient_civs"], crossDomain: [{ target: "lang.linguistics_basics", label: "Language/culture" }] },
      { id: "media_literacy", name: "Media Literacy", tier: 5, prereqs: ["critical_analysis"], crossDomain: [{ target: "tech.social_media_lit", label: "Digital media" }, { target: "lang.rhetoric", label: "Rhetoric in media" }] },
      { id: "intl_relations", name: "International Relations", tier: 5, prereqs: ["world_hist_modern", "political_sci", "macroeconomics"], crossDomain: [] },
      // TIER 6
      { id: "ap_history", name: "AP-Level History", tier: 6, prereqs: ["us_hist_modern", "world_hist_modern", "critical_analysis"], crossDomain: [{ target: "lang.academic_writing", label: "DBQ essays" }] },
      { id: "constitutional_law", name: "Constitutional Law", tier: 6, prereqs: ["civics_gov", "us_hist_modern"], crossDomain: [{ target: "life.legal_literacy", label: "Legal framework" }] },
      { id: "comparative_gov", name: "Comparative Government", tier: 6, prereqs: ["political_sci", "world_hist_modern"], crossDomain: [] },
      { id: "behavioral_econ", name: "Behavioral Economics", tier: 6, prereqs: ["microeconomics", "macroeconomics"], crossDomain: [{ target: "math.probability_theory", label: "Decision models" }] },
      { id: "geopolitics", name: "Geopolitics", tier: 6, prereqs: ["intl_relations", "world_hist_modern", "map_globe"], crossDomain: [] },
      { id: "historiography", name: "Historiography", tier: 6, prereqs: ["ap_history", "critical_analysis"], crossDomain: [{ target: "lang.discourse_analysis", label: "Narrative analysis" }] },
      // TIER 7
      { id: "political_philosophy", name: "Political Philosophy", tier: 7, prereqs: ["comparative_gov", "constitutional_law"], crossDomain: [{ target: "religion.philosophical_theology", label: "Philosophy of religion" }] },
      { id: "economic_theory", name: "Economic Theory", tier: 7, prereqs: ["behavioral_econ", "macroeconomics"], crossDomain: [{ target: "math.derivatives", label: "Optimization" }] },
      { id: "foreign_policy", name: "Foreign Policy Analysis", tier: 7, prereqs: ["intl_relations", "geopolitics", "comparative_gov"], crossDomain: [] },
      { id: "demographic_analysis", name: "Demographic Analysis", tier: 7, prereqs: ["sociology_basics", "macroeconomics"], crossDomain: [{ target: "math.probability_theory", label: "Statistics" }] },
      { id: "urban_planning", name: "Urban Planning", tier: 7, prereqs: ["macroeconomics", "sociology_basics"], crossDomain: [{ target: "creative.architecture", label: "Urban design" }] },
      { id: "public_policy", name: "Public Policy", tier: 7, prereqs: ["macroeconomics", "political_sci", "behavioral_econ"], crossDomain: [{ target: "life.project_management", label: "Policy implementation" }] },
      // TIER 8
      { id: "game_theory", name: "Game Theory", tier: 8, prereqs: ["economic_theory"], crossDomain: [{ target: "math.probability_theory", label: "Expected values" }] },
      { id: "intl_law", name: "International Law", tier: 8, prereqs: ["constitutional_law", "intl_relations", "comparative_gov"], crossDomain: [] },
      { id: "dev_economics", name: "Development Economics", tier: 8, prereqs: ["economic_theory", "demographic_analysis"], crossDomain: [{ target: "religion.missiology", label: "Development missions" }] },
      { id: "political_economy", name: "Political Economy", tier: 8, prereqs: ["economic_theory", "political_philosophy"], crossDomain: [] },
      { id: "research_methodology", name: "Research Methodology", tier: 8, prereqs: ["ap_history", "demographic_analysis"], crossDomain: [{ target: "lang.research_papers", label: "Academic writing" }] },
      { id: "diplomatic_strategy", name: "Diplomatic Strategy", tier: 8, prereqs: ["foreign_policy", "intl_law", "game_theory"], crossDomain: [{ target: "life.adv_negotiation", label: "Negotiation" }] },
    ]
  },
  {
    id: "religion",
    name: "Christianity",
    color: "#8B5CF6",
    colorDark: "#6D28D9",
    icon: "✝",
    skills: [
      // TIER 1
      { id: "bible_stories", name: "Bible Stories", tier: 1, prereqs: [], crossDomain: [{ target: "lang.listening_comp", label: "Story listening" }, { target: "social.timeline_chrono", label: "Biblical timeline" }] },
      { id: "prayer_basics", name: "Prayer Basics", tier: 1, prereqs: [], crossDomain: [{ target: "lang.listening_comp", label: "Reflective listening" }] },
      { id: "gods_love", name: "God's Love", tier: 1, prereqs: ["bible_stories"], crossDomain: [{ target: "life.basic_manners", label: "Love for others" }] },
      { id: "church_community", name: "Church Community", tier: 1, prereqs: ["gods_love"], crossDomain: [{ target: "social.community_awareness", label: "Community" }] },
      { id: "worship", name: "Worship", tier: 1, prereqs: ["church_community", "gods_love"], crossDomain: [{ target: "creative.singing_along", label: "Worship music" }] },
      { id: "ten_commandments", name: "Ten Commandments", tier: 1, prereqs: ["bible_stories", "gods_love"], crossDomain: [{ target: "social.rules_laws", label: "Moral law" }] },
      // TIER 2
      { id: "ot_survey", name: "Old Testament Survey", tier: 2, prereqs: ["bible_stories"], crossDomain: [{ target: "social.ancient_civs", label: "Ancient Near East" }, { target: "lang.reading_fluency", label: "Bible reading" }] },
      { id: "nt_survey", name: "New Testament Survey", tier: 2, prereqs: ["bible_stories"], crossDomain: [{ target: "social.ancient_civs", label: "Roman Empire" }] },
      { id: "key_verses", name: "Key Verse Memorization", tier: 2, prereqs: ["ot_survey", "nt_survey"], crossDomain: [{ target: "lang.reading_fluency", label: "Recitation" }] },
      { id: "parables", name: "Parables of Jesus", tier: 2, prereqs: ["nt_survey", "gods_love"], crossDomain: [{ target: "lang.figurative_lang", label: "Allegory" }] },
      { id: "fruits_spirit", name: "Fruits of the Spirit", tier: 2, prereqs: ["gods_love", "ten_commandments"], crossDomain: [{ target: "life.emotional_reg", label: "Character development" }] },
      { id: "church_hist_basics", name: "Church History Basics", tier: 2, prereqs: ["nt_survey", "church_community"], crossDomain: [{ target: "social.timeline_chrono", label: "Historical timeline" }] },
      { id: "baptism", name: "Baptism Understanding", tier: 2, prereqs: ["gods_love", "church_community"], crossDomain: [] },
      // TIER 3
      { id: "biblical_geography", name: "Biblical Geography", tier: 3, prereqs: ["ot_survey", "nt_survey"], crossDomain: [{ target: "social.world_geography", label: "Middle East geography" }] },
      { id: "life_of_christ", name: "Life of Christ Study", tier: 3, prereqs: ["nt_survey"], crossDomain: [{ target: "lang.reading_comp", label: "Gospel analysis" }] },
      { id: "acts_early_church", name: "Acts & Early Church", tier: 3, prereqs: ["nt_survey", "church_hist_basics"], crossDomain: [{ target: "social.ancient_civs", label: "Roman world" }] },
      { id: "psalms_wisdom", name: "Psalms & Wisdom Literature", tier: 3, prereqs: ["ot_survey"], crossDomain: [{ target: "creative.poetry", label: "Hebrew poetry" }, { target: "lang.figurative_lang", label: "Poetic devices" }] },
      { id: "personal_devotion", name: "Personal Devotion", tier: 3, prereqs: ["prayer_basics", "key_verses"], crossDomain: [{ target: "life.time_management", label: "Daily discipline" }] },
      { id: "christian_ethics", name: "Christian Ethics Basics", tier: 3, prereqs: ["ten_commandments", "fruits_spirit"], crossDomain: [{ target: "social.civics_gov", label: "Ethical governance" }] },
      { id: "denominational", name: "Denominational Awareness", tier: 3, prereqs: ["church_hist_basics", "church_community"], crossDomain: [{ target: "social.cultural_awareness", label: "Religious diversity" }] },
      // TIER 4
      { id: "hermeneutics", name: "Hermeneutics", tier: 4, prereqs: ["life_of_christ", "psalms_wisdom"], crossDomain: [{ target: "lang.literary_analysis", label: "Text interpretation" }, { target: "lang.essay_writing", label: "Exegetical writing" }] },
      { id: "systematic_theo_basic", name: "Systematic Theology Basics", tier: 4, prereqs: ["ot_survey", "nt_survey", "christian_ethics"], crossDomain: [{ target: "lang.essay_writing", label: "Theological writing" }] },
      { id: "church_hist_reformation", name: "Church History: Reformation", tier: 4, prereqs: ["church_hist_basics"], crossDomain: [{ target: "social.world_hist_medieval", label: "Medieval/Renaissance" }] },
      { id: "apologetics", name: "Apologetics", tier: 4, prereqs: ["systematic_theo_basic", "christian_ethics"], crossDomain: [{ target: "lang.debate", label: "Argumentation" }, { target: "math.proofs", label: "Logical reasoning" }] },
      { id: "spiritual_disciplines", name: "Spiritual Disciplines", tier: 4, prereqs: ["personal_devotion", "fruits_spirit"], crossDomain: [{ target: "life.stress_management", label: "Contemplative practice" }, { target: "fitness.yoga", label: "Body-spirit connection" }] },
      { id: "mission_evangelism", name: "Mission & Evangelism", tier: 4, prereqs: ["apologetics", "church_community"], crossDomain: [{ target: "social.world_geography", label: "Global missions" }, { target: "lang.public_speaking_basic", label: "Sharing faith" }] },
      // TIER 5
      { id: "ot_exegesis", name: "Old Testament Exegesis", tier: 5, prereqs: ["hermeneutics", "ot_survey"], crossDomain: [{ target: "lang.academic_writing", label: "Exegetical papers" }] },
      { id: "nt_exegesis", name: "New Testament Exegesis", tier: 5, prereqs: ["hermeneutics", "nt_survey"], crossDomain: [{ target: "lang.academic_writing", label: "Exegetical papers" }] },
      { id: "comparative_theology", name: "Comparative Theology", tier: 5, prereqs: ["systematic_theo_basic", "denominational"], crossDomain: [{ target: "social.world_religions_overview", label: "Interfaith context" }] },
      { id: "christian_philosophy", name: "Christian Philosophy", tier: 5, prereqs: ["apologetics", "systematic_theo_basic"], crossDomain: [{ target: "social.political_philosophy", label: "Political theology" }] },
      { id: "pastoral_care", name: "Pastoral Care", tier: 5, prereqs: ["spiritual_disciplines", "christian_ethics"], crossDomain: [{ target: "life.stress_management", label: "Counseling basics" }] },
      { id: "homiletics", name: "Homiletics (Preaching)", tier: 5, prereqs: ["hermeneutics", "mission_evangelism"], crossDomain: [{ target: "lang.rhetoric", label: "Persuasive speech" }, { target: "lang.public_speaking_basic", label: "Public speaking" }] },
      // TIER 6
      { id: "biblical_languages_basic", name: "Biblical Hebrew & Greek Basics", tier: 6, prereqs: ["ot_exegesis", "nt_exegesis"], crossDomain: [{ target: "lang.linguistics_basics", label: "Language structure" }] },
      { id: "historical_theology", name: "Historical Theology", tier: 6, prereqs: ["church_hist_reformation", "systematic_theo_basic"], crossDomain: [{ target: "social.historiography", label: "Historical methods" }] },
      { id: "ethics_moral_theo", name: "Ethics & Moral Theology", tier: 6, prereqs: ["christian_ethics", "christian_philosophy"], crossDomain: [{ target: "social.political_philosophy", label: "Justice theory" }] },
      { id: "ecclesiology", name: "Ecclesiology", tier: 6, prereqs: ["systematic_theo_basic", "church_hist_reformation"], crossDomain: [{ target: "social.sociology_basics", label: "Church as institution" }] },
      { id: "missiology", name: "Missiology", tier: 6, prereqs: ["mission_evangelism", "comparative_theology"], crossDomain: [{ target: "social.anthropology", label: "Cultural context" }, { target: "social.dev_economics", label: "Development" }] },
      { id: "counseling", name: "Christian Counseling", tier: 6, prereqs: ["pastoral_care"], crossDomain: [{ target: "life.stress_management", label: "Mental health" }] },
      // TIER 7
      { id: "biblical_languages_adv", name: "Advanced Biblical Languages", tier: 7, prereqs: ["biblical_languages_basic"], crossDomain: [{ target: "lang.translation_theory", label: "Translation" }] },
      { id: "systematic_theology", name: "Systematic Theology", tier: 7, prereqs: ["historical_theology", "ot_exegesis", "nt_exegesis"], crossDomain: [{ target: "lang.thesis_development", label: "Thesis writing" }] },
      { id: "philosophical_theology", name: "Philosophical Theology", tier: 7, prereqs: ["christian_philosophy", "ethics_moral_theo"], crossDomain: [{ target: "social.political_philosophy", label: "Philosophy" }] },
      { id: "liturgical_studies", name: "Liturgical Studies", tier: 7, prereqs: ["ecclesiology", "historical_theology"], crossDomain: [{ target: "creative.choreography", label: "Liturgical movement" }] },
      { id: "church_admin", name: "Church Administration", tier: 7, prereqs: ["ecclesiology", "pastoral_care"], crossDomain: [{ target: "life.project_management", label: "Management" }, { target: "life.leadership", label: "Leadership" }] },
      { id: "interfaith_dialogue", name: "Interfaith Dialogue", tier: 7, prereqs: ["comparative_theology", "ethics_moral_theo"], crossDomain: [{ target: "social.intl_relations", label: "Diplomacy" }] },
      // TIER 8
      { id: "original_lang_scholarship", name: "Original Language Scholarship", tier: 8, prereqs: ["biblical_languages_adv"], crossDomain: [{ target: "lang.academic_publishing", label: "Publishing" }] },
      { id: "theology_of_culture", name: "Theology of Culture", tier: 8, prereqs: ["systematic_theology", "philosophical_theology"], crossDomain: [{ target: "creative.art_direction", label: "Faith & art" }] },
      { id: "public_theology", name: "Public Theology", tier: 8, prereqs: ["systematic_theology", "ethics_moral_theo"], crossDomain: [{ target: "social.public_policy", label: "Faith & policy" }] },
      { id: "academic_biblical_criticism", name: "Academic Biblical Criticism", tier: 8, prereqs: ["original_lang_scholarship", "systematic_theology"], crossDomain: [{ target: "lang.literary_theory", label: "Critical theory" }] },
      { id: "theological_research", name: "Theological Research & Publishing", tier: 8, prereqs: ["academic_biblical_criticism"], crossDomain: [{ target: "lang.academic_publishing", label: "Academic publishing" }] },
    ]
  },
  {
    id: "life",
    name: "Life Skills",
    color: "#EF4444",
    colorDark: "#B91C1C",
    icon: "🏠",
    skills: [
      // TIER 1
      { id: "personal_hygiene", name: "Personal Hygiene", tier: 1, prereqs: [], crossDomain: [{ target: "fitness.balance", label: "Body awareness" }] },
      { id: "dressing_self", name: "Dressing Self", tier: 1, prereqs: [], crossDomain: [] },
      { id: "basic_manners", name: "Basic Manners", tier: 1, prereqs: [], crossDomain: [{ target: "social.community_awareness", label: "Social norms" }, { target: "religion.gods_love", label: "Love for others" }] },
      { id: "following_instructions", name: "Following Instructions", tier: 1, prereqs: [], crossDomain: [{ target: "lang.listening_comp", label: "Listening" }] },
      { id: "sharing_turns", name: "Sharing & Taking Turns", tier: 1, prereqs: [], crossDomain: [{ target: "social.sharing_coop", label: "Cooperation" }] },
      { id: "basic_safety", name: "Basic Safety", tier: 1, prereqs: ["following_instructions"], crossDomain: [] },
      { id: "telling_time", name: "Telling Time", tier: 1, prereqs: [], crossDomain: [{ target: "math.time_math", label: "Clock math" }] },
      { id: "recognizing_coins", name: "Recognizing Coins", tier: 1, prereqs: [], crossDomain: [{ target: "math.counting", label: "Counting" }] },
      // TIER 2
      { id: "chores", name: "Chores", tier: 2, prereqs: ["following_instructions", "basic_manners"], crossDomain: [] },
      { id: "basic_cooking", name: "Basic Cooking", tier: 2, prereqs: ["basic_safety", "personal_hygiene", "following_instructions"], crossDomain: [] },
      { id: "money_counting", name: "Money Counting", tier: 2, prereqs: ["recognizing_coins"], crossDomain: [{ target: "math.money_math", label: "Arithmetic with money" }] },
      { id: "stranger_danger", name: "Stranger Danger", tier: 2, prereqs: ["basic_safety", "basic_manners"], crossDomain: [] },
      { id: "fire_safety", name: "Fire Safety", tier: 2, prereqs: ["basic_safety", "following_instructions"], crossDomain: [] },
      { id: "phone_skills", name: "Phone Skills", tier: 2, prereqs: ["following_instructions", "basic_manners"], crossDomain: [{ target: "tech.basic_app_usage", label: "Device usage" }] },
      { id: "basic_first_aid", name: "Basic First Aid", tier: 2, prereqs: ["basic_safety", "fire_safety"], crossDomain: [{ target: "fitness.injury_prevention", label: "Injury response" }] },
      // TIER 3
      { id: "laundry", name: "Laundry", tier: 3, prereqs: ["chores"], crossDomain: [] },
      { id: "meal_planning", name: "Meal Planning & Cooking", tier: 3, prereqs: ["basic_cooking", "money_counting"], crossDomain: [{ target: "fitness.nutrition_fitness", label: "Nutrition" }] },
      { id: "budgeting", name: "Budgeting Basics", tier: 3, prereqs: ["money_counting"], crossDomain: [{ target: "math.percentages", label: "Interest rates" }] },
      { id: "time_management", name: "Time Management", tier: 3, prereqs: ["telling_time", "following_instructions"], crossDomain: [{ target: "religion.personal_devotion", label: "Daily discipline" }] },
      { id: "study_skills", name: "Study Skills", tier: 3, prereqs: ["time_management", "following_instructions"], crossDomain: [{ target: "lang.note_taking", label: "Note-taking" }] },
      { id: "internet_safety", name: "Internet Safety", tier: 3, prereqs: ["stranger_danger"], crossDomain: [{ target: "tech.digital_citizenship", label: "Online safety" }] },
      { id: "conflict_resolution", name: "Conflict Resolution", tier: 3, prereqs: ["basic_manners", "sharing_turns"], crossDomain: [{ target: "social.sociology_basics", label: "Group dynamics" }] },
      { id: "emotional_reg", name: "Emotional Regulation", tier: 3, prereqs: ["basic_manners"], crossDomain: [{ target: "religion.fruits_spirit", label: "Self-control" }, { target: "fitness.yoga", label: "Mind-body" }] },
      // TIER 4
      { id: "grocery_shopping", name: "Grocery Shopping", tier: 4, prereqs: ["meal_planning", "budgeting"], crossDomain: [{ target: "math.percentages", label: "Discounts/tax" }] },
      { id: "banking", name: "Banking", tier: 4, prereqs: ["budgeting"], crossDomain: [{ target: "math.decimals", label: "Account math" }] },
      { id: "resume_writing", name: "Resume Writing", tier: 4, prereqs: ["study_skills"], crossDomain: [{ target: "lang.paragraph_writing", label: "Writing" }, { target: "tech.word_processing", label: "Formatting" }] },
      { id: "job_interview", name: "Job Interview Skills", tier: 4, prereqs: ["resume_writing"], crossDomain: [{ target: "lang.public_speaking_basic", label: "Speaking" }] },
      { id: "drivers_ed", name: "Driver's Education", tier: 4, prereqs: ["basic_safety", "time_management"], crossDomain: [] },
      { id: "home_maintenance", name: "Home Maintenance Basics", tier: 4, prereqs: ["chores", "basic_safety"], crossDomain: [{ target: "tech.basic_troubleshooting", label: "Problem solving" }] },
      { id: "nutrition", name: "Nutrition", tier: 4, prereqs: ["meal_planning"], crossDomain: [{ target: "fitness.nutrition_fitness", label: "Sports nutrition" }] },
      { id: "stress_management", name: "Stress Management", tier: 4, prereqs: ["emotional_reg"], crossDomain: [{ target: "fitness.yoga", label: "Mindfulness" }, { target: "religion.spiritual_disciplines", label: "Contemplation" }] },
      // TIER 5
      { id: "taxes", name: "Taxes & Filing", tier: 5, prereqs: ["banking", "budgeting"], crossDomain: [{ target: "math.percentages", label: "Tax rates" }] },
      { id: "insurance", name: "Insurance Understanding", tier: 5, prereqs: ["banking"], crossDomain: [] },
      { id: "apartment_hunting", name: "Apartment Hunting", tier: 5, prereqs: ["banking", "budgeting"], crossDomain: [] },
      { id: "adv_cooking", name: "Advanced Cooking", tier: 5, prereqs: ["meal_planning", "nutrition"], crossDomain: [{ target: "creative.pottery_sculpture", label: "Craft mastery" }] },
      { id: "financial_planning", name: "Financial Planning", tier: 5, prereqs: ["taxes", "insurance", "banking"], crossDomain: [{ target: "math.exponential_log", label: "Compound interest" }, { target: "social.macroeconomics", label: "Economic context" }] },
      { id: "networking", name: "Networking", tier: 5, prereqs: ["job_interview"], crossDomain: [{ target: "lang.prof_communication", label: "Professional writing" }] },
      { id: "self_advocacy", name: "Self-Advocacy", tier: 5, prereqs: ["conflict_resolution", "emotional_reg"], crossDomain: [{ target: "lang.persuasive_writing", label: "Persuasion" }] },
      { id: "critical_thinking", name: "Critical Thinking", tier: 5, prereqs: ["study_skills", "conflict_resolution"], crossDomain: [{ target: "math.proofs", label: "Logical reasoning" }, { target: "social.critical_analysis", label: "Source analysis" }] },
      // TIER 6
      { id: "home_buying", name: "Home Buying", tier: 6, prereqs: ["financial_planning", "apartment_hunting"], crossDomain: [{ target: "social.constitutional_law", label: "Property law" }] },
      { id: "investing", name: "Investing Basics", tier: 6, prereqs: ["financial_planning"], crossDomain: [{ target: "math.exponential_log", label: "Growth models" }, { target: "social.macroeconomics", label: "Markets" }] },
      { id: "career_planning", name: "Career Planning", tier: 6, prereqs: ["networking", "financial_planning"], crossDomain: [{ target: "lang.prof_communication", label: "Career writing" }] },
      { id: "parenting", name: "Parenting Skills", tier: 6, prereqs: ["emotional_reg", "nutrition", "stress_management"], crossDomain: [{ target: "religion.pastoral_care", label: "Family ministry" }] },
      { id: "legal_literacy", name: "Legal Literacy", tier: 6, prereqs: ["critical_thinking", "taxes"], crossDomain: [{ target: "social.constitutional_law", label: "Legal system" }] },
      { id: "contract_understanding", name: "Contract Understanding", tier: 6, prereqs: ["legal_literacy"], crossDomain: [] },
      { id: "emergency_prep", name: "Emergency Preparedness", tier: 6, prereqs: ["fire_safety", "basic_first_aid", "home_maintenance"], crossDomain: [{ target: "fitness.injury_prevention", label: "Physical readiness" }] },
      { id: "leadership", name: "Leadership", tier: 6, prereqs: ["networking", "self_advocacy", "conflict_resolution"], crossDomain: [{ target: "religion.church_admin", label: "Church leadership" }, { target: "fitness.coaching_basics", label: "Team leadership" }] },
      // TIER 7
      { id: "adv_investing", name: "Advanced Investing", tier: 7, prereqs: ["investing"], crossDomain: [{ target: "math.probability_theory", label: "Risk models" }] },
      { id: "estate_planning", name: "Estate Planning", tier: 7, prereqs: ["legal_literacy", "investing"], crossDomain: [] },
      { id: "entrepreneurship", name: "Entrepreneurship", tier: 7, prereqs: ["career_planning", "leadership", "financial_planning"], crossDomain: [{ target: "tech.software_eng", label: "Tech startups" }, { target: "creative.portfolio_dev", label: "Brand building" }] },
      { id: "mentoring", name: "Mentoring", tier: 7, prereqs: ["leadership", "parenting"], crossDomain: [{ target: "religion.pastoral_care", label: "Discipleship" }] },
      { id: "adv_negotiation", name: "Advanced Negotiation", tier: 7, prereqs: ["self_advocacy", "leadership"], crossDomain: [{ target: "social.diplomatic_strategy", label: "Diplomacy" }] },
      { id: "project_management", name: "Project Management", tier: 7, prereqs: ["leadership", "time_management"], crossDomain: [{ target: "tech.software_eng", label: "Agile/Scrum" }] },
      { id: "policy_engagement", name: "Public Policy Engagement", tier: 7, prereqs: ["legal_literacy", "critical_thinking"], crossDomain: [{ target: "social.public_policy", label: "Policy making" }] },
      // TIER 8
      { id: "wealth_management", name: "Wealth Management", tier: 8, prereqs: ["adv_investing", "estate_planning"], crossDomain: [] },
      { id: "business_strategy", name: "Business Strategy", tier: 8, prereqs: ["entrepreneurship", "adv_negotiation"], crossDomain: [{ target: "social.game_theory", label: "Strategic thinking" }] },
      { id: "exec_leadership", name: "Executive Leadership", tier: 8, prereqs: ["entrepreneurship", "mentoring", "project_management"], crossDomain: [] },
      { id: "philanthropy", name: "Philanthropy", tier: 8, prereqs: ["wealth_management", "mentoring"], crossDomain: [{ target: "religion.missiology", label: "Charitable missions" }] },
      { id: "legacy_planning", name: "Legacy Planning", tier: 8, prereqs: ["estate_planning", "wealth_management"], crossDomain: [{ target: "religion.theology_of_culture", label: "Lasting impact" }] },
    ]
  },
  {
    id: "creative",
    name: "Creative",
    color: "#EC4899",
    colorDark: "#BE185D",
    icon: "🎨",
    skills: [
      // TIER 1
      { id: "scribbling", name: "Scribbling & Drawing", tier: 1, prereqs: [], crossDomain: [] },
      { id: "coloring", name: "Coloring", tier: 1, prereqs: ["scribbling"], crossDomain: [] },
      { id: "rhythm_beat", name: "Rhythm & Beat", tier: 1, prereqs: [], crossDomain: [{ target: "fitness.coordination", label: "Motor rhythm" }] },
      { id: "singing_along", name: "Singing Along", tier: 1, prereqs: [], crossDomain: [{ target: "religion.worship", label: "Worship songs" }] },
      { id: "imaginative_play", name: "Imaginative Play", tier: 1, prereqs: [], crossDomain: [{ target: "lang.basic_vocab", label: "Vocabulary building" }] },
      { id: "building_blocks", name: "Building Blocks", tier: 1, prereqs: [], crossDomain: [{ target: "math.basic_geometry", label: "Spatial reasoning" }] },
      { id: "finger_painting", name: "Finger Painting", tier: 1, prereqs: [], crossDomain: [] },
      // TIER 2
      { id: "basic_drawing", name: "Basic Drawing", tier: 2, prereqs: ["scribbling", "coloring"], crossDomain: [{ target: "lang.handwriting", label: "Fine motor" }] },
      { id: "crafts", name: "Crafts", tier: 2, prereqs: ["scribbling", "coloring"], crossDomain: [] },
      { id: "basic_instrument", name: "Basic Musical Instrument", tier: 2, prereqs: ["rhythm_beat"], crossDomain: [] },
      { id: "singing_choir", name: "Singing & Choir", tier: 2, prereqs: ["singing_along", "rhythm_beat"], crossDomain: [{ target: "religion.worship", label: "Church choir" }] },
      { id: "storytelling_creative", name: "Storytelling", tier: 2, prereqs: ["imaginative_play"], crossDomain: [{ target: "lang.reading_fluency", label: "Narrative skills" }] },
      { id: "dance_basics", name: "Dance Basics", tier: 2, prereqs: ["rhythm_beat"], crossDomain: [{ target: "fitness.coordination", label: "Movement" }, { target: "social.cultural_awareness", label: "Cultural dance" }] },
      { id: "photography_basics", name: "Photography Basics", tier: 2, prereqs: [], crossDomain: [{ target: "tech.basic_app_usage", label: "Camera apps" }] },
      // TIER 3
      { id: "sketching_shading", name: "Sketching & Shading", tier: 3, prereqs: ["basic_drawing"], crossDomain: [] },
      { id: "painting", name: "Painting", tier: 3, prereqs: ["basic_drawing", "finger_painting"], crossDomain: [] },
      { id: "music_theory_basic", name: "Music Theory Basics", tier: 3, prereqs: ["basic_instrument", "rhythm_beat"], crossDomain: [{ target: "math.fractions", label: "Time signatures" }, { target: "math.ratios", label: "Intervals" }] },
      { id: "instrument_proficiency", name: "Instrument Proficiency", tier: 3, prereqs: ["basic_instrument", "music_theory_basic"], crossDomain: [] },
      { id: "acting_theater", name: "Acting & Theater", tier: 3, prereqs: ["imaginative_play", "storytelling_creative"], crossDomain: [{ target: "lang.reading_comp", label: "Script reading" }] },
      { id: "creative_writing_art", name: "Creative Writing", tier: 3, prereqs: ["storytelling_creative"], crossDomain: [{ target: "lang.paragraph_writing", label: "Writing craft" }] },
      { id: "pottery_sculpture", name: "Pottery & Sculpture", tier: 3, prereqs: ["crafts", "building_blocks"], crossDomain: [] },
      { id: "graphic_design_basic", name: "Graphic Design Basics", tier: 3, prereqs: ["basic_drawing"], crossDomain: [{ target: "tech.basic_app_usage", label: "Design software" }] },
      // TIER 4
      { id: "design_principles", name: "Composition & Design Principles", tier: 4, prereqs: ["sketching_shading", "graphic_design_basic"], crossDomain: [{ target: "math.basic_geometry", label: "Golden ratio" }] },
      { id: "color_theory", name: "Color Theory", tier: 4, prereqs: ["painting"], crossDomain: [{ target: "math.proportions", label: "Color mixing" }] },
      { id: "music_theory_intermediate", name: "Intermediate Music Theory", tier: 4, prereqs: ["music_theory_basic"], crossDomain: [] },
      { id: "ensemble_band", name: "Ensemble & Band", tier: 4, prereqs: ["instrument_proficiency"], crossDomain: [{ target: "fitness.team_sports_intro", label: "Teamwork" }] },
      { id: "directing", name: "Directing", tier: 4, prereqs: ["acting_theater"], crossDomain: [{ target: "life.leadership", label: "Leadership" }] },
      { id: "screenwriting", name: "Screenwriting", tier: 4, prereqs: ["creative_writing_art", "acting_theater"], crossDomain: [{ target: "lang.creative_writing", label: "Narrative craft" }] },
      { id: "digital_art", name: "Digital Art", tier: 4, prereqs: ["graphic_design_basic", "sketching_shading"], crossDomain: [{ target: "tech.basic_app_usage", label: "Software tools" }] },
      { id: "film_video_basics", name: "Film & Video Basics", tier: 4, prereqs: ["photography_basics", "storytelling_creative"], crossDomain: [{ target: "tech.basic_app_usage", label: "Video software" }] },
      // TIER 5
      { id: "adv_drawing_painting", name: "Advanced Drawing & Painting", tier: 5, prereqs: ["design_principles", "color_theory"], crossDomain: [] },
      { id: "music_composition", name: "Music Composition", tier: 5, prereqs: ["music_theory_intermediate", "instrument_proficiency"], crossDomain: [{ target: "math.sequences_series", label: "Patterns/structure" }] },
      { id: "audio_production", name: "Audio Production", tier: 5, prereqs: ["music_theory_intermediate"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Audio software" }] },
      { id: "adv_acting", name: "Advanced Acting", tier: 5, prereqs: ["acting_theater", "directing"], crossDomain: [{ target: "life.emotional_reg", label: "Emotional depth" }] },
      { id: "poetry", name: "Poetry", tier: 5, prereqs: ["creative_writing_art"], crossDomain: [{ target: "lang.figurative_lang", label: "Poetic devices" }, { target: "religion.psalms_wisdom", label: "Sacred poetry" }] },
      { id: "animation", name: "Animation", tier: 5, prereqs: ["digital_art", "film_video_basics"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Code animation" }] },
      { id: "ux_ui_design", name: "UX/UI Design", tier: 5, prereqs: ["digital_art", "design_principles"], crossDomain: [{ target: "tech.web_dev_basics", label: "Web interfaces" }] },
      { id: "fashion_design", name: "Fashion Design", tier: 5, prereqs: ["design_principles", "color_theory"], crossDomain: [] },
      // TIER 6
      { id: "portfolio_dev", name: "Portfolio Development", tier: 6, prereqs: ["adv_drawing_painting"], crossDomain: [{ target: "life.career_planning", label: "Career branding" }] },
      { id: "music_production", name: "Music Production", tier: 6, prereqs: ["music_composition", "audio_production"], crossDomain: [{ target: "tech.prog_fundamentals", label: "DAW skills" }] },
      { id: "film_production", name: "Film Production", tier: 6, prereqs: ["film_video_basics", "directing", "screenwriting"], crossDomain: [{ target: "life.project_management", label: "Production management" }] },
      { id: "adv_sculpture", name: "Advanced Sculpture", tier: 6, prereqs: ["pottery_sculpture", "design_principles"], crossDomain: [] },
      { id: "art_history", name: "Art History", tier: 6, prereqs: ["adv_drawing_painting"], crossDomain: [{ target: "social.world_hist_medieval", label: "Cultural context" }] },
      { id: "choreography", name: "Choreography", tier: 6, prereqs: ["dance_basics"], crossDomain: [{ target: "fitness.coordination", label: "Movement design" }, { target: "religion.liturgical_studies", label: "Liturgical dance" }] },
      { id: "game_design", name: "Game Design", tier: 6, prereqs: ["digital_art", "screenwriting"], crossDomain: [{ target: "tech.oop", label: "Game programming" }, { target: "math.probability_theory", label: "Game balance" }] },
      { id: "architecture", name: "Architecture Basics", tier: 6, prereqs: ["design_principles", "pottery_sculpture"], crossDomain: [{ target: "math.solid_geometry", label: "3D geometry" }, { target: "social.urban_planning", label: "Urban design" }] },
      // TIER 7
      { id: "exhibition_gallery", name: "Exhibition & Gallery Work", tier: 7, prereqs: ["portfolio_dev"], crossDomain: [{ target: "life.entrepreneurship", label: "Art business" }] },
      { id: "orchestration", name: "Orchestration", tier: 7, prereqs: ["music_composition", "ensemble_band"], crossDomain: [] },
      { id: "film_post_prod", name: "Film Editing & Post-Production", tier: 7, prereqs: ["film_production"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Effects software" }] },
      { id: "mixed_media", name: "Mixed Media", tier: 7, prereqs: ["adv_drawing_painting", "adv_sculpture"], crossDomain: [] },
      { id: "art_criticism", name: "Art Criticism", tier: 7, prereqs: ["art_history", "literary_analysis_creative"], crossDomain: [{ target: "lang.semiotics", label: "Visual semiotics" }] },
      { id: "prof_performance", name: "Professional Performance", tier: 7, prereqs: ["adv_acting", "music_production"], crossDomain: [{ target: "life.career_planning", label: "Performance career" }] },
      { id: "sound_design", name: "Sound Design", tier: 7, prereqs: ["audio_production", "music_production"], crossDomain: [{ target: "tech.prog_fundamentals", label: "Audio programming" }] },
      { id: "industrial_design", name: "Industrial Design", tier: 7, prereqs: ["design_principles", "architecture"], crossDomain: [{ target: "tech.system_design", label: "Systems thinking" }] },
      // TIER 8
      { id: "art_direction", name: "Art Direction", tier: 8, prereqs: ["portfolio_dev", "design_principles"], crossDomain: [{ target: "life.exec_leadership", label: "Creative leadership" }] },
      { id: "conducting", name: "Conducting", tier: 8, prereqs: ["orchestration", "music_theory_intermediate"], crossDomain: [{ target: "life.leadership", label: "Ensemble leadership" }] },
      { id: "cinematography", name: "Cinematography", tier: 8, prereqs: ["film_post_prod", "photography_basics"], crossDomain: [] },
      { id: "installation_art", name: "Installation Art", tier: 8, prereqs: ["mixed_media", "adv_sculpture"], crossDomain: [] },
      { id: "curation", name: "Curation", tier: 8, prereqs: ["art_criticism", "exhibition_gallery"], crossDomain: [] },
      { id: "master_craftsmanship", name: "Master Craftsmanship", tier: 8, prereqs: ["adv_sculpture", "mixed_media"], crossDomain: [] },
    ]
  },
  {
    id: "tech",
    name: "Technology",
    color: "#06B6D4",
    colorDark: "#0E7490",
    icon: "💻",
    skills: [
      // TIER 1
      { id: "mouse_keyboard", name: "Mouse & Keyboard Skills", tier: 1, prereqs: [], crossDomain: [{ target: "fitness.coordination", label: "Fine motor" }] },
      { id: "device_onoff", name: "Turning On/Off Devices", tier: 1, prereqs: [], crossDomain: [] },
      { id: "basic_app_usage", name: "Basic App Usage", tier: 1, prereqs: ["mouse_keyboard", "device_onoff"], crossDomain: [] },
      { id: "internet_browsing", name: "Internet Browsing", tier: 1, prereqs: ["mouse_keyboard"], crossDomain: [] },
      { id: "typing_basics", name: "Typing Basics", tier: 1, prereqs: ["mouse_keyboard"], crossDomain: [{ target: "lang.handwriting", label: "Writing modes" }] },
      // TIER 2
      { id: "file_management", name: "File Management", tier: 2, prereqs: ["basic_app_usage", "mouse_keyboard"], crossDomain: [] },
      { id: "word_processing", name: "Word Processing", tier: 2, prereqs: ["basic_app_usage", "typing_basics"], crossDomain: [{ target: "lang.handwriting", label: "Digital writing" }] },
      { id: "email", name: "Email", tier: 2, prereqs: ["internet_browsing", "basic_app_usage", "typing_basics"], crossDomain: [{ target: "lang.sentence_structure", label: "Written communication" }] },
      { id: "internet_search", name: "Internet Search Skills", tier: 2, prereqs: ["internet_browsing"], crossDomain: [{ target: "lang.research_skills", label: "Research" }, { target: "social.critical_analysis", label: "Source evaluation" }] },
      { id: "digital_citizenship", name: "Digital Citizenship", tier: 2, prereqs: ["internet_browsing", "email"], crossDomain: [{ target: "life.internet_safety", label: "Online safety" }, { target: "social.citizenship_basics", label: "Digital civics" }] },
      { id: "basic_troubleshooting", name: "Basic Troubleshooting", tier: 2, prereqs: ["device_onoff", "basic_app_usage"], crossDomain: [] },
      { id: "presentation_software", name: "Presentation Software", tier: 2, prereqs: ["word_processing", "basic_app_usage"], crossDomain: [{ target: "lang.public_speaking_basic", label: "Presenting" }] },
      // TIER 3
      { id: "spreadsheets", name: "Spreadsheets", tier: 3, prereqs: ["word_processing", "basic_app_usage"], crossDomain: [{ target: "math.graphing", label: "Data charting" }, { target: "life.budgeting", label: "Budget tracking" }] },
      { id: "intro_coding", name: "Intro to Coding", tier: 3, prereqs: ["basic_app_usage", "internet_search"], crossDomain: [{ target: "math.order_of_ops", label: "Sequential logic" }] },
      { id: "touch_typing", name: "Touch Typing", tier: 3, prereqs: ["typing_basics"], crossDomain: [] },
      { id: "cloud_storage", name: "Cloud Storage", tier: 3, prereqs: ["file_management", "internet_browsing"], crossDomain: [] },
      { id: "social_media_lit", name: "Social Media Literacy", tier: 3, prereqs: ["digital_citizenship", "email", "internet_search"], crossDomain: [{ target: "social.media_literacy", label: "Media analysis" }] },
      { id: "hardware_basics", name: "Hardware Basics", tier: 3, prereqs: ["device_onoff", "basic_troubleshooting"], crossDomain: [] },
      { id: "digital_security", name: "Digital Security", tier: 3, prereqs: ["digital_citizenship", "email"], crossDomain: [{ target: "life.internet_safety", label: "Safety practices" }] },
      // TIER 4
      { id: "prog_fundamentals", name: "Programming Fundamentals", tier: 4, prereqs: ["intro_coding", "touch_typing"], crossDomain: [{ target: "math.variables_expr", label: "Variables" }, { target: "math.functions", label: "Functions" }] },
      { id: "web_dev_basics", name: "Web Development Basics", tier: 4, prereqs: ["intro_coding"], crossDomain: [{ target: "creative.graphic_design_basic", label: "Visual design" }] },
      { id: "database_concepts", name: "Database Concepts", tier: 4, prereqs: ["spreadsheets"], crossDomain: [] },
      { id: "networking_basics", name: "Networking Basics", tier: 4, prereqs: ["hardware_basics", "digital_security"], crossDomain: [] },
      { id: "operating_systems", name: "Operating Systems", tier: 4, prereqs: ["file_management", "hardware_basics"], crossDomain: [] },
      { id: "version_control", name: "Version Control", tier: 4, prereqs: ["file_management"], crossDomain: [] },
      // TIER 5
      { id: "oop", name: "Object-Oriented Programming", tier: 5, prereqs: ["prog_fundamentals"], crossDomain: [] },
      { id: "python_js", name: "Python / JavaScript", tier: 5, prereqs: ["prog_fundamentals"], crossDomain: [] },
      { id: "full_stack", name: "Full Stack Web Development", tier: 5, prereqs: ["web_dev_basics", "python_js"], crossDomain: [{ target: "creative.ux_ui_design", label: "UI design" }] },
      { id: "sql", name: "SQL", tier: 5, prereqs: ["database_concepts", "prog_fundamentals"], crossDomain: [] },
      { id: "apis", name: "APIs", tier: 5, prereqs: ["prog_fundamentals", "networking_basics"], crossDomain: [] },
      { id: "mobile_dev", name: "Mobile App Development", tier: 5, prereqs: ["oop", "python_js"], crossDomain: [] },
      { id: "linux_cli", name: "Linux & Command Line", tier: 5, prereqs: ["operating_systems"], crossDomain: [] },
      // TIER 6
      { id: "data_structures", name: "Data Structures & Algorithms", tier: 6, prereqs: ["oop", "python_js"], crossDomain: [{ target: "math.discrete_math", label: "Graph theory" }] },
      { id: "software_eng", name: "Software Engineering", tier: 6, prereqs: ["oop", "version_control", "full_stack"], crossDomain: [{ target: "life.project_management", label: "Agile methods" }, { target: "lang.technical_writing", label: "Documentation" }] },
      { id: "cloud_computing", name: "Cloud Computing", tier: 6, prereqs: ["linux_cli", "networking_basics", "cloud_storage"], crossDomain: [] },
      { id: "cybersecurity", name: "Cybersecurity", tier: 6, prereqs: ["digital_security", "networking_basics", "linux_cli"], crossDomain: [] },
      { id: "devops", name: "DevOps", tier: 6, prereqs: ["linux_cli", "cloud_computing", "version_control"], crossDomain: [] },
      { id: "ml_basics", name: "Machine Learning Basics", tier: 6, prereqs: ["python_js", "data_structures"], crossDomain: [{ target: "math.linear_algebra", label: "Linear algebra" }, { target: "math.probability_theory", label: "Probability" }] },
      { id: "computer_architecture", name: "Computer Architecture", tier: 6, prereqs: ["hardware_basics", "operating_systems"], crossDomain: [] },
      // TIER 7
      { id: "system_design", name: "System Design", tier: 7, prereqs: ["software_eng", "cloud_computing"], crossDomain: [] },
      { id: "distributed_systems", name: "Distributed Systems", tier: 7, prereqs: ["system_design", "data_structures"], crossDomain: [] },
      { id: "advanced_ml", name: "Advanced ML & AI", tier: 7, prereqs: ["ml_basics"], crossDomain: [{ target: "math.multivariable_calc", label: "Optimization" }, { target: "math.linear_algebra", label: "Matrices" }] },
      { id: "compiler_design", name: "Compiler Design", tier: 7, prereqs: ["data_structures", "computer_architecture"], crossDomain: [] },
      { id: "computer_graphics", name: "Computer Graphics", tier: 7, prereqs: ["data_structures"], crossDomain: [{ target: "math.matrices", label: "Transform matrices" }, { target: "math.vectors_math", label: "3D vectors" }, { target: "creative.animation", label: "Digital animation" }] },
      { id: "robotics", name: "Robotics", tier: 7, prereqs: ["ml_basics", "computer_architecture"], crossDomain: [{ target: "fitness.biomechanics", label: "Movement modeling" }] },
      { id: "blockchain", name: "Blockchain", tier: 7, prereqs: ["data_structures", "cybersecurity"], crossDomain: [] },
      // TIER 8
      { id: "quantum_computing", name: "Quantum Computing", tier: 8, prereqs: ["computer_architecture", "data_structures"], crossDomain: [{ target: "math.linear_algebra", label: "Quantum states" }] },
      { id: "advanced_ai_research", name: "Advanced AI Research", tier: 8, prereqs: ["advanced_ml"], crossDomain: [{ target: "math.probability_theory", label: "Bayesian methods" }] },
      { id: "cryptography", name: "Cryptography", tier: 8, prereqs: ["cybersecurity", "data_structures"], crossDomain: [{ target: "math.number_theory", label: "RSA/primes" }, { target: "math.abstract_algebra", label: "Groups/fields" }] },
      { id: "formal_verification", name: "Formal Verification", tier: 8, prereqs: ["compiler_design"], crossDomain: [{ target: "math.proofs", label: "Formal proofs" }] },
      { id: "hci_research", name: "HCI Research", tier: 8, prereqs: ["system_design", "advanced_ml"], crossDomain: [{ target: "creative.ux_ui_design", label: "Design research" }, { target: "fitness.adaptive_athletics", label: "Adaptive interfaces" }] },
      { id: "comp_biology", name: "Computational Biology", tier: 8, prereqs: ["advanced_ml", "data_structures"], crossDomain: [{ target: "fitness.sports_science", label: "Biomolecular analysis" }] },
    ]
  },
  {
    id: "fitness",
    name: "Physical Fitness",
    color: "#F97316",
    colorDark: "#C2410C",
    icon: "💪",
    skills: [
      // TIER 1
      { id: "crawling", name: "Crawling", tier: 1, prereqs: [], crossDomain: [] },
      { id: "walking", name: "Walking", tier: 1, prereqs: ["crawling"], crossDomain: [] },
      { id: "running", name: "Running", tier: 1, prereqs: ["walking"], crossDomain: [] },
      { id: "jumping", name: "Jumping", tier: 1, prereqs: ["walking"], crossDomain: [] },
      { id: "throwing", name: "Throwing", tier: 1, prereqs: [], crossDomain: [{ target: "math.basic_geometry", label: "Trajectory" }] },
      { id: "catching", name: "Catching", tier: 1, prereqs: [], crossDomain: [] },
      { id: "balance", name: "Balance", tier: 1, prereqs: ["crawling", "walking"], crossDomain: [] },
      { id: "coordination", name: "Coordination", tier: 1, prereqs: ["balance"], crossDomain: [{ target: "creative.rhythm_beat", label: "Motor rhythm" }, { target: "tech.mouse_keyboard", label: "Fine motor" }] },
      // TIER 2
      { id: "swimming_basics", name: "Swimming Basics", tier: 2, prereqs: ["coordination", "balance"], crossDomain: [] },
      { id: "cycling", name: "Cycling", tier: 2, prereqs: ["balance", "coordination"], crossDomain: [{ target: "life.basic_safety", label: "Road safety" }] },
      { id: "ball_sports_basics", name: "Ball Sports Basics", tier: 2, prereqs: ["throwing", "catching", "running"], crossDomain: [] },
      { id: "gymnastics_basics", name: "Gymnastics Basics", tier: 2, prereqs: ["balance", "coordination", "jumping"], crossDomain: [{ target: "creative.dance_basics", label: "Movement" }] },
      { id: "stretching", name: "Stretching", tier: 2, prereqs: ["balance"], crossDomain: [] },
      { id: "bodyweight_exercises", name: "Bodyweight Exercises", tier: 2, prereqs: ["running", "jumping", "balance"], crossDomain: [] },
      { id: "team_sports_intro", name: "Team Sports Introduction", tier: 2, prereqs: ["ball_sports_basics"], crossDomain: [{ target: "social.sharing_coop", label: "Teamwork" }, { target: "life.conflict_resolution", label: "Sportsmanship" }] },
      // TIER 3
      { id: "sport_specific", name: "Sport-Specific Skills", tier: 3, prereqs: ["team_sports_intro"], crossDomain: [] },
      { id: "endurance", name: "Endurance Training", tier: 3, prereqs: ["running", "cycling"], crossDomain: [{ target: "life.time_management", label: "Training schedule" }] },
      { id: "flexibility", name: "Flexibility Training", tier: 3, prereqs: ["stretching"], crossDomain: [{ target: "creative.dance_basics", label: "Range of motion" }] },
      { id: "strength_basics", name: "Strength Training Basics", tier: 3, prereqs: ["bodyweight_exercises"], crossDomain: [] },
      { id: "nutrition_fitness", name: "Nutrition for Fitness", tier: 3, prereqs: ["endurance", "strength_basics"], crossDomain: [{ target: "life.nutrition", label: "Dietary planning" }] },
      { id: "warmup_cooldown", name: "Warm-Up & Cool-Down", tier: 3, prereqs: ["stretching", "endurance"], crossDomain: [] },
      { id: "sportsmanship", name: "Sportsmanship", tier: 3, prereqs: ["team_sports_intro"], crossDomain: [{ target: "life.conflict_resolution", label: "Fair play" }, { target: "religion.christian_ethics", label: "Moral conduct" }] },
      // TIER 4
      { id: "weight_training", name: "Weight Training", tier: 4, prereqs: ["strength_basics"], crossDomain: [] },
      { id: "interval_training", name: "Interval Training", tier: 4, prereqs: ["endurance", "warmup_cooldown"], crossDomain: [] },
      { id: "sport_strategy", name: "Sport Strategy", tier: 4, prereqs: ["sport_specific"], crossDomain: [{ target: "social.game_theory", label: "Strategic thinking" }] },
      { id: "injury_prevention", name: "Injury Prevention", tier: 4, prereqs: ["warmup_cooldown", "strength_basics"], crossDomain: [{ target: "life.basic_first_aid", label: "First aid" }] },
      { id: "adv_swimming", name: "Advanced Swimming", tier: 4, prereqs: ["swimming_basics", "endurance"], crossDomain: [] },
      { id: "martial_arts", name: "Martial Arts Basics", tier: 4, prereqs: ["balance", "coordination", "strength_basics"], crossDomain: [{ target: "religion.spiritual_disciplines", label: "Discipline" }] },
      { id: "yoga", name: "Yoga", tier: 4, prereqs: ["flexibility", "balance"], crossDomain: [{ target: "life.stress_management", label: "Mindfulness" }, { target: "religion.spiritual_disciplines", label: "Contemplation" }] },
      { id: "cross_training", name: "Cross-Training", tier: 4, prereqs: ["endurance", "strength_basics", "flexibility"], crossDomain: [] },
      // TIER 5
      { id: "periodization", name: "Periodization Training", tier: 5, prereqs: ["weight_training", "interval_training"], crossDomain: [{ target: "life.time_management", label: "Planning cycles" }] },
      { id: "sports_psychology", name: "Sports Psychology", tier: 5, prereqs: ["sport_strategy", "sportsmanship"], crossDomain: [{ target: "life.stress_management", label: "Mental training" }] },
      { id: "adv_strength", name: "Advanced Strength Training", tier: 5, prereqs: ["weight_training"], crossDomain: [] },
      { id: "competition_prep", name: "Competition Preparation", tier: 5, prereqs: ["periodization", "nutrition_fitness"], crossDomain: [{ target: "life.time_management", label: "Peak scheduling" }] },
      { id: "coaching_basics", name: "Coaching Basics", tier: 5, prereqs: ["sport_specific", "sport_strategy"], crossDomain: [{ target: "life.leadership", label: "Team leadership" }] },
      { id: "mobility_recovery", name: "Mobility & Recovery", tier: 5, prereqs: ["flexibility", "injury_prevention"], crossDomain: [] },
      { id: "sport_conditioning", name: "Sport-Specific Conditioning", tier: 5, prereqs: ["cross_training", "sport_specific"], crossDomain: [] },
      // TIER 6
      { id: "adv_sport_strategy", name: "Advanced Sport Strategy", tier: 6, prereqs: ["sport_strategy", "sports_psychology"], crossDomain: [] },
      { id: "personal_training", name: "Personal Training & Coaching", tier: 6, prereqs: ["coaching_basics", "adv_strength"], crossDomain: [{ target: "life.career_planning", label: "Fitness career" }] },
      { id: "exercise_physiology", name: "Exercise Physiology", tier: 6, prereqs: ["adv_strength", "nutrition_fitness"], crossDomain: [{ target: "math.derivatives", label: "Rate of change" }] },
      { id: "sports_nutrition", name: "Sports Nutrition", tier: 6, prereqs: ["nutrition_fitness", "periodization"], crossDomain: [{ target: "life.nutrition", label: "Advanced diet" }] },
      { id: "rehabilitation", name: "Rehabilitation", tier: 6, prereqs: ["injury_prevention", "mobility_recovery"], crossDomain: [] },
      { id: "endurance_events", name: "Endurance Events", tier: 6, prereqs: ["periodization", "endurance", "competition_prep"], crossDomain: [] },
      // TIER 7
      { id: "athletic_optimization", name: "Athletic Performance Optimization", tier: 7, prereqs: ["exercise_physiology", "sports_nutrition"], crossDomain: [{ target: "tech.advanced_ml", label: "Performance analytics" }] },
      { id: "biomechanics", name: "Biomechanics", tier: 7, prereqs: ["exercise_physiology"], crossDomain: [{ target: "math.trig_ratios", label: "Angle analysis" }, { target: "tech.computer_graphics", label: "Motion capture" }] },
      { id: "kinesiology", name: "Kinesiology", tier: 7, prereqs: ["biomechanics", "exercise_physiology"], crossDomain: [] },
      { id: "strength_conditioning_prog", name: "Strength & Conditioning Programming", tier: 7, prereqs: ["adv_strength", "periodization", "personal_training"], crossDomain: [] },
      { id: "sports_medicine", name: "Sports Medicine Basics", tier: 7, prereqs: ["rehabilitation", "exercise_physiology"], crossDomain: [] },
      { id: "elite_competition", name: "Elite Competition", tier: 7, prereqs: ["competition_prep", "adv_sport_strategy"], crossDomain: [] },
      // TIER 8
      { id: "professional_athletics", name: "Professional Athletics", tier: 8, prereqs: ["elite_competition", "athletic_optimization"], crossDomain: [] },
      { id: "sports_science", name: "Sports Science Research", tier: 8, prereqs: ["biomechanics", "kinesiology"], crossDomain: [{ target: "math.diff_equations", label: "Growth models" }, { target: "tech.comp_biology", label: "Biomolecular" }] },
      { id: "exercise_prescription", name: "Exercise Prescription", tier: 8, prereqs: ["sports_medicine", "kinesiology"], crossDomain: [] },
      { id: "performance_analytics", name: "Performance Analytics", tier: 8, prereqs: ["athletic_optimization"], crossDomain: [{ target: "tech.advanced_ml", label: "ML analytics" }, { target: "math.probability_theory", label: "Statistical models" }] },
      { id: "elite_coaching", name: "Elite Coaching Certification", tier: 8, prereqs: ["strength_conditioning_prog", "sports_medicine"], crossDomain: [{ target: "life.mentoring", label: "Athlete development" }] },
      { id: "adaptive_athletics", name: "Adaptive Athletics", tier: 8, prereqs: ["exercise_prescription", "personal_training"], crossDomain: [{ target: "tech.hci_research", label: "Adaptive tech" }] },
    ]
  }
];
