-- Step 1: Clusters (69 rows)
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_basic_arithmetic', 'Math', 'Basic Arithmetic', '#ffd700', '{"x":1100,"y":2640}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_intermediate_arithmetic', 'Math', 'Intermediate Arithmetic', '#87ceeb', '{"x":1000,"y":2060}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_advanced_arithmetic', 'Math', 'Advanced Arithmetic', '#dda0dd', '{"x":600,"y":1620}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_pre_algebra', 'Math', 'Pre-Algebra', '#98fb98', '{"x":580,"y":1260}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_geometry', 'Math', 'Geometry', '#ffa07a', '{"x":1800,"y":840}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_algebra_1', 'Math', 'Algebra 1', '#20b2aa', '{"x":760,"y":1020}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_algebra_2', 'Math', 'Algebra 2', '#ff6347', '{"x":560,"y":760}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_pre_calculus', 'Math', 'Pre-Calculus', '#daa520', '{"x":1200,"y":540}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_calculus', 'Math', 'Calculus', '#f0e68c', '{"x":1000,"y":240}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_advanced_mathematics', 'Math', 'Advanced Mathematics', '#9370db', '{"x":760,"y":50}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_specialized_topics', 'Math', 'Specialized Topics', '#32cd32', '{"x":190,"y":100}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_mastery_and_research', 'Math', 'Mastery and Research', '#ff69b4', '{"x":580,"y":-60}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('math_final_specializations', 'Math', 'Final Specializations', '#00ced1', '{"x":650,"y":-170}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_core_foundations', 'Technology', 'Core Foundations', '#00ff00', '{"x":1391,"y":3256}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_basic_programming', 'Technology', 'Basic Programming', '#87ceeb', '{"x":1229,"y":2880}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_intermediate_programming', 'Technology', 'Intermediate Programming', '#dda0dd', '{"x":1237,"y":2582}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_intermediate_development', 'Technology', 'Intermediate Development', '#98fb98', '{"x":1156,"y":2290}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_advanced_development', 'Technology', 'Advanced Development', '#ffa07a', '{"x":1593,"y":1918}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_web_development', 'Technology', 'Web Development', '#ff6347', '{"x":2372,"y":1397}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_systems_programming', 'Technology', 'Systems Programming', '#20b2aa', '{"x":483,"y":1286}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_software_engineering', 'Technology', 'Software Engineering', '#daa520', '{"x":858,"y":1301}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_full_stack_development', 'Technology', 'Full Stack Development', '#f0e68c', '{"x":1200,"y":1300}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_game_development', 'Technology', 'Game Development', '#9370db', '{"x":1898,"y":1147}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_data_science', 'Technology', 'Data Science', '#32cd32', '{"x":1552,"y":1382}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_mechanical_maker', 'Technology', 'Mechanical Maker', '#ff4500', '{"x":988,"y":4063}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_electric_explorer', 'Technology', 'Electric Explorer', '#00bfff', '{"x":596,"y":4190}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_code_commander', 'Technology', 'Code Commander', '#32cd32', '{"x":1253,"y":4177}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_tech_designer', 'Technology', 'Tech Designer', '#9370db', '{"x":1160,"y":4558}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('technology_innovator___problem_solver', 'Technology', 'Innovator & Problem Solver', '#ffd700', '{"x":460,"y":4590}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_core', 'Creative', 'Core', '#ffd700', 'null') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_art_fundamentals', 'Creative', 'Art Fundamentals', '#87ceeb', '{"x":977,"y":455}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_traditional_media', 'Creative', 'Traditional Media', '#dda0dd', '{"x":765,"y":738}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_digital_art', 'Creative', 'Digital Art', '#98fb98', '{"x":1688,"y":752}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_design', 'Creative', 'Design', '#ffa07a', '{"x":1486,"y":458}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_animation', 'Creative', 'Animation', '#20b2aa', '{"x":1385,"y":1079}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_creative_technology', 'Creative', 'Creative Technology', '#ff6347', '{"x":982,"y":1087}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_professional', 'Creative', 'Professional', '#daa520', '{"x":1762,"y":383}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('creative_specialized', 'Creative', 'Specialized', '#f0e68c', '{"x":726,"y":484}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('language_reading_foundations', 'Language', 'Reading Foundations', '#ffd700', '{"x":1177,"y":1355}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('language_reading_skills', 'Language', 'Reading Skills', '#87ceeb', '{"x":1200,"y":950}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('language_comprehension', 'Language', 'Comprehension', '#dda0dd', '{"x":1266,"y":555}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('language_literary_analysis', 'Language', 'Literary Analysis', '#98fb98', '{"x":865,"y":638}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('language_advanced_reading', 'Language', 'Advanced Reading', '#ffa07a', '{"x":1588,"y":252}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_core_science', 'Science', 'Core Science', '#ffd700', 'null') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_scientific_thinking', 'Science', 'Scientific Thinking', '#87ceeb', '{"x":1177,"y":655}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_physical_science', 'Science', 'Physical Science', '#dda0dd', '{"x":865,"y":838}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_physics', 'Science', 'Physics', '#98fb98', '{"x":1588,"y":752}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_life_science', 'Science', 'Life Science', '#ffa07a', '{"x":1285,"y":1279}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('science_earth_science', 'Science', 'Earth Science', '#20b2aa', '{"x":726,"y":484}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('bible_foundations', 'Bible', 'Foundations', '#c9a96e', '{"x":1200,"y":1753}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('bible_fluency', 'Bible', 'Fluency', '#c9a96e', '{"x":1200,"y":1353}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('bible_application', 'Bible', 'Application', '#c9a96e', '{"x":1263,"y":938}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('bible_integration', 'Bible', 'Integration', '#c9a96e', '{"x":1339,"y":554}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('bible_mastery', 'Bible', 'Mastery', '#c9a96e', '{"x":1200,"y":175}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('lifeskills_foundations', 'LifeSkills', 'Foundations', '#98fb98', '{"x":1200,"y":1753}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('lifeskills_fluency', 'LifeSkills', 'Fluency', '#98fb98', '{"x":1200,"y":1360}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('lifeskills_application', 'LifeSkills', 'Application', '#98fb98', '{"x":1289,"y":946}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('lifeskills_integration', 'LifeSkills', 'Integration', '#98fb98', '{"x":1289,"y":546}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('lifeskills_mastery', 'LifeSkills', 'Mastery', '#98fb98', '{"x":1200,"y":193}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('physical_foundations', 'Physical', 'Foundations', '#ff6347', '{"x":1200,"y":1753}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('physical_fluency', 'Physical', 'Fluency', '#ff6347', '{"x":1200,"y":1353}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('physical_application', 'Physical', 'Application', '#ff6347', '{"x":1446,"y":943}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('physical_integration', 'Physical', 'Integration', '#ff6347', '{"x":1250,"y":546}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('physical_mastery', 'Physical', 'Mastery', '#ff6347', '{"x":1283,"y":163}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('social_foundations', 'Social', 'Foundations', '#ffa07a', '{"x":1200,"y":1753}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('social_fluency', 'Social', 'Fluency', '#ffa07a', '{"x":1200,"y":1353}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('social_application', 'Social', 'Application', '#ffa07a', '{"x":1289,"y":946}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('social_integration', 'Social', 'Integration', '#ffa07a', '{"x":1339,"y":554}') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_clusters (id, domain, name, color, label_position) VALUES ('social_mastery', 'Social', 'Mastery', '#ffa07a', '{"x":1283,"y":163}') ON CONFLICT (id) DO NOTHING;
