-- Additive: 22 new English/Language curriculum nodes (E28–E49)
-- and their prerequisite edges. Idempotent (ON CONFLICT DO NOTHING).
-- Runs after seed_2_nodes/seed_3_edges so the tables and referenced nodes exist.

INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E28', 'Parts of Speech', 'Language', 'Branch', 'Fluency', '', false, 'Language: Fluency', '', 'Identify and use the eight parts of speech', '["Identify and use the eight parts of speech"]', '{}', '{"x":2402,"y":999,"z_group":1,"color_cluster":"Language: Fluency"}', NULL, NULL, 'E28', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E29', 'Context Clues', 'Language', 'Branch', 'Fluency', '', false, 'Language: Fluency', '', 'Use surrounding text to determine word meaning', '["Use surrounding text to determine word meaning"]', '{}', '{"x":2552,"y":879,"z_group":1,"color_cluster":"Language: Fluency"}', NULL, NULL, 'E29', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E30', 'Genre Study', 'Language', 'Branch', 'Fluency', '', false, 'Language: Fluency', '', 'Identify and distinguish literary genres', '["Identify and distinguish literary genres"]', '{}', '{"x":2702,"y":999,"z_group":1,"color_cluster":"Language: Fluency"}', NULL, NULL, 'E30', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E31', 'Punctuation & Capitalization', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Apply correct punctuation and capitalization', '["Apply correct punctuation and capitalization"]', '{}', '{"x":2642,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E31', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E32', 'Clauses & Phrases', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Identify clauses and phrases and combine sentences', '["Identify clauses and phrases and combine sentences"]', '{}', '{"x":2792,"y":740,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E32', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E33', 'Roots & Affixes', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Use roots, prefixes, and suffixes to decode meaning', '["Use roots, prefixes, and suffixes to decode meaning"]', '{}', '{"x":2942,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E33', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E34', 'Text Structures', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Identify nonfiction text structures', '["Identify nonfiction text structures"]', '{}', '{"x":3092,"y":740,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E34', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E35', 'Author''s Purpose', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Determine an author''s purpose and point of view', '["Determine an author''s purpose and point of view"]', '{}', '{"x":3242,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E35', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E36', 'Summarizing', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Summarize a text in your own words', '["Summarize a text in your own words"]', '{}', '{"x":3392,"y":740,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E36', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E37', 'Narrative Writing', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Write an engaging narrative with sequence and detail', '["Write an engaging narrative with sequence and detail"]', '{}', '{"x":3542,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E37', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E38', 'Informative Writing', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Write a clear informative or explanatory text', '["Write a clear informative or explanatory text"]', '{}', '{"x":3692,"y":740,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E38', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E39', 'Writing Process', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Plan, draft, revise, edit, and publish writing', '["Plan, draft, revise, edit, and publish writing"]', '{}', '{"x":3842,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E39', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E40', 'Drama & Theater', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Identify the elements of drama', '["Identify the elements of drama"]', '{}', '{"x":3992,"y":740,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E40', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E41', 'Mood & Tone', 'Language', 'Branch', 'Application', '', false, 'Language: Application', '', 'Distinguish mood and tone in a text', '["Distinguish mood and tone in a text"]', '{}', '{"x":4142,"y":860,"z_group":1,"color_cluster":"Language: Application"}', NULL, NULL, 'E41', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E42', 'Active Listening & Discussion', 'Language', 'Branch', 'Integration', '', false, 'Language: Integration', '', 'Listen actively and participate in discussion', '["Listen actively and participate in discussion"]', '{}', '{"x":2642,"y":723,"z_group":1,"color_cluster":"Language: Integration"}', NULL, NULL, 'E42', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E43', 'MLA & APA Citation', 'Language', 'Branch', 'Integration', '', false, 'Language: Integration', '', 'Cite sources correctly in MLA and APA', '["Cite sources correctly in MLA and APA"]', '{}', '{"x":2792,"y":603,"z_group":1,"color_cluster":"Language: Integration"}', NULL, NULL, 'E43', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E44', 'Rhetorical Analysis', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Analyze how a text persuades its audience', '["Analyze how a text persuades its audience"]', '{}', '{"x":2152,"y":344,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E44', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E45', 'Synthesis Writing', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Synthesize multiple sources into one argument', '["Synthesize multiple sources into one argument"]', '{}', '{"x":2302,"y":224,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E45', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E46', 'Technical & Professional Writing', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Produce clear technical and professional documents', '["Produce clear technical and professional documents"]', '{}', '{"x":2452,"y":344,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E46', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E47', 'Formal Logic', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Evaluate arguments using premises and conclusions', '["Evaluate arguments using premises and conclusions"]', '{}', '{"x":2602,"y":224,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E47', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E48', 'Etymology & Word Origins', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Trace word origins to understand meaning', '["Trace word origins to understand meaning"]', '{}', '{"x":2752,"y":344,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E48', 'csv') ON CONFLICT (id) DO NOTHING;
INSERT INTO curriculum_nodes (id, title, domain, path_type, stage, grade_band, primary_path, cluster, description, demonstration, mastery_criteria, evidence_types, visual, legacy_name, legacy_subject, csv_id, source) VALUES ('E49', 'Literary Criticism', 'Language', 'Branch', 'Mastery', '', false, 'Language: Mastery', '', 'Interpret texts through critical lenses', '["Interpret texts through critical lenses"]', '{}', '{"x":2902,"y":224,"z_group":1,"color_cluster":"Language: Mastery"}', NULL, NULL, 'E49', 'csv') ON CONFLICT (id) DO NOTHING;

INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1330', 'E7', 'E28', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1331', 'L-006', 'E29', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1332', 'E21', 'E30', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1333', 'E11', 'E31', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1334', 'E7', 'E32', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1335', 'L-006', 'E33', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1336', 'E9', 'E34', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1337', 'E9', 'E35', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1338', 'E5', 'E36', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1339', 'E8', 'E37', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1340', 'E8', 'E38', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1341', 'E10', 'E39', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1342', 'E21', 'E40', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1343', 'E22', 'E41', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1344', 'E16', 'E42', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1345', 'E14', 'E43', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1346', 'E15', 'E44', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1347', 'E18', 'E45', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1348', 'E17', 'E46', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1349', 'E19', 'E47', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1350', 'E33', 'E48', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
INSERT INTO curriculum_edges (id, from_node, to_node, edge_type) VALUES ('E1351', 'E23', 'E49', 'prerequisite_hard') ON CONFLICT (from_node, to_node, edge_type) DO NOTHING;
